### ISSUE TITLE
Demo PDOException

### ISSUE THREAD

**Issue by nikeshbhagat** [taviroquai/laraproto#1]
First - great work. It's a very practical foundation for my laravel/angular app.  

I'm sure you're already aware of this, but I noticed that your Demo page is throwing a PDOException - just thought I'd give you the heads up. The project is easily decipherable nonetheless.

Excellent contribution to laravel!

**Comment by taviroquai** [comment]
Hi,

Thanks for the warning. It makes some time that I don't visit laraproto demo :p

Yes. The structure client/server e very clean and easy to improve it.
I'm glad you like it. :+1:
