### ISSUE TITLE
TokenMismatchException : Csrf Token Exception

### ISSUE THREAD

**Issue by eissasoubhi** [taviroquai/laraproto#2]
Hello,
i really love this application it makes working with Laravel more funny and easy.
especially the security features, but **sometimes** i get _Csrf Token Exception_ even though i'm connected with right permissions.

example :
if i try to add/edit a content i get this from JSON response :
![csrf](https://cloud.githubusercontent.com/assets/4972714/13459662/94affbf0-e075-11e5-9b1c-464767d6fee0.jpg)

when i get this exception i refresh the content form to generate a new csrf token, and it works

**Comment by taviroquai** [comment]
Does this happen everytime you click to edit? Whats your environment? OS? webserver?

**Comment by eissasoubhi** [comment]
Not everytime, just somtimes especially for pages that have not been used for a while.
i'm working on local using Windows 8.1 with WAMP installed.

**Comment by taviroquai** [comment]
My dev environment is Ubuntu 14.04. Ah the backoffice has a lot of ajax... maybe it happens when the token/session expires... (the user may be editing for a long time?). Just throwing thoughts...

**Comment by eissasoubhi** [comment]
haha no i'm just used to open many tabs while i'm programming, i'll test it in my home computer it's Ubuntu 14.04 too, i've checked out that issue on google and it turned out that many other programmers have same problem, i think it's laravel 5.1 issue when working with ajax, i'll try to use header to send the token instead of input like recommended in https://laravel.com/docs/5.1/routing#csrf-x-csrf-token. 
for now i just added the edit page uri to $except attribute of VerifyCsrfToken Middleware.

**Comment by taviroquai** [comment]
Hmm... I like the solution provided by your link in Laravel docs. I may refactor all backoffice Ajax to use it.

**Comment by eissasoubhi** [comment]
that will be helpful

**Comment by taviroquai** [comment]
Hi @netfox01 please check if this fixes the issue. Thanks!

**Comment by eissasoubhi** [comment]
Hi, i tried to fix the issue by adding your code to the layout file but i didn't work.
the problem i have is the token is regenerated in the session after uploading couple images via ajax,
so the next image wont be uploaded because Laravel tries to compare the old csrf token (when i first opened new content form) with the new one regenerated in the session.
i dug into Laravel files and i figured out that the token is being regenerated  by this function in
`vendor/laravel/framework/src/illuminate/session/store.php` file :

``` php
public function start()
    {
        $this->loadSession();

        if (! $this->has('_token')) {
            $this->regenerateToken();
        }

        return $this->started = true;
    }
```

here is an example :

click the images for a full screen

**test part 1**
![img_ajax_upload](https://cloud.githubusercontent.com/assets/4972714/13666931/57a644ea-e6b4-11e5-864c-ff285721f5cf.gif)

**test part 2**
![img_ajax_upload2](https://cloud.githubusercontent.com/assets/4972714/13666932/57b102a4-e6b4-11e5-9ad5-daf0817483ad.gif)

**Comment by taviroquai** [comment]
Hi, I've just tried the ajax upload of several pictures on the online Demo and could not reproduce the error. Have a try here http://taviroquai.com/laraproto/public/

**Comment by eissasoubhi** [comment]
yes, you are absolutely right, i tested it in my app first commit and i had no error, i'm sure i messed up somewhere, i couldn't find where. 
i'll just stick with adding URIs to $except attribute of VerifyCsrfToken Middleware.
