### ISSUE TITLE
Random Exception “File could not be uploaded: missing temporary directory.”

### ISSUE THREAD

**Issue by eissasoubhi** [taviroquai/laraproto#4]
Hi,

i have an issue with image uploading.
i get FileException that occurs randomly after uploading some/none images.
It's not a problem of image size, the same image that's uploaded once could not be uploaded next time.
The Exception message :

``` php
FileException in UploadedFile.php line 235:
File could not be uploaded: missing temporary directory.
```

that happen only in the Hosting Server, it works fine in Local.

My local is running on windows.

Here is the Exception in screenshot
![fileuploaderror](https://cloud.githubusercontent.com/assets/4972714/13812669/cc18143e-eb7d-11e5-80e8-b0ee940f7a1d.jpg)

i checked the demo and it worked fine, i just thought you may experienced the same issue or have an idea about it.

Thanks.

**Comment by taviroquai** [comment]
Hello :)

I google for it and it seems a php configuration problem.

Some ideas:
1. Check your php.ini settings on the parameter _upload_tmp_dir_ and check path permissions
2. Try to change the setting in (1) and give the webserver permissions

Cheers,
Marco

**Comment by eissasoubhi** [comment]
Thank you

**Comment by taviroquai** [comment]
You are welcome Eissa :)
