### ISSUE TITLE
Can't connect to demo with default admin user

### ISSUE THREAD

**Issue by corentingi** [taviroquai/laraproto#5]
Hi,
Looks like the default admin password has been changed.
Would be nice if it wasn't possible on the demo! :smiley: 

Thanks

**Comment by taviroquai** [comment]
Thanks for the alert :)

Well I just added pemissions and set to deny to Admin users. Of course an Admin can change the deny to allow :)

**Comment by taviroquai** [comment]
You can now login.

**Comment by corentingi** [comment]
Thanks!
